spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: jdbc:h2:mem:memdb
    username: sa
    password: p
    driverClassName: org.h2.Driver
  h2:
    console:
      # http://localhost:8000/h2-console
      enabled: true