apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demok8s-app
  ports:
    - protocol: TCP
      name: web
      port: 8088
      targetPort: 8000
    - protocol: TCP
      name: actuator
      port: 9099
      targetPort: 9090
  type: ClusterIP
#  clusterIP: None #взамен type: ClusterIp

